controller_list:
  - name: "neo_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint