# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# As MoveIt! does not support jerk limits, the acceleration limits provided here are the highest values that guarantee
# that no jerk limits will be violated. More precisely, applying Euler differentiation in the worst case (from min accel
# to max accel in 1 ms) the acceleration limits are the ones that satisfy
# max_jerk = (max_acceleration - min_acceleration) / 0.001

joint_limits:
  first_joint:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  second_joint:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  third_joint:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  fourth_joint:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  fifth_joint:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  sixth_joint:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  gripper_finger1_joint:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
