 controller_list:
  - name: NX63A1
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint
  - name: ag95
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger1_joint

